[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version"

[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npm run docs:build"
  ignore = "./scripts/docs-check.sh"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[redirects]]
  from = "/*"
  to = "/zh/:splat"
  status = 301
  force = true
  conditions = {Language = ["zh","zh-CN"], Country = ["CN","HK","TW","MO"]}
