blank_issues_enabled: false
contact_links:
  - name: Need Help
    url: https://github.com/Zhengqbbb/cz-git/discussions/new
    about: Please ask questions in Discussion.

  - name: FAQ
    url: https://cz-git.qbenben.com/faq/
    about: Frequently Asked Questions | 常见问题
